apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-gateway
  namespace: {{ .Release.Namespace }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{{ toYaml .Values.gateway.httpHosts | indent 4 }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
{{ toYaml .Values.gateway.httpsHosts | indent 4 }}
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-cert-wc-secret
