{{- range $key, $val := .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{  $val.name }}
  namespace: {{ $val.namespace}}
  annotations:
{{ toYaml $val.annotations | indent 4 }}
spec:
  tls:
  - hosts:
{{ toYaml $val.hosts | indent 4 }}
    secretName: {{ $val.secretName }}
  rules:
{{ toYaml $val.rules | indent 4 }}
{{- end}}

