apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  user: {{.Values.secrets.userName}}
  password: {{.Values.secrets.password}}
