apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
{{ toYaml .Values.hosts | indent 4 }}
  gateways:
  - istio-ingress/sample-gateway
  http:
    - route:
      - destination:
          port:
            number: 20001
          host: kiali.{{ .Release.Namespace}}.svc.cluster.local
