apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: cert-manager
spec:
  commonName: {{ .Values.certificate.commonName }} 
  dnsNames:
  {{ toYaml .Values.certificate.dnsNames | indent 10 }}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: {{ .Values.certificate.secretName }}
