apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: traefik
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/instance: traefik-traefik
