hosts:
  - dex.example.com
dex:
  https:
    # -- Enable the HTTPS endpoint.
    enabled: false
  # -- Application configuration.
  # See the [official documentation](https://dexidp.io/docs/).
  config:
    connectors:
    - type: github
      # Required field for connector id.
      id: github
      # Required field for connector name.
      name: GitHub
      config:
        # Credentials can be string literals or pulled from the environment.
        clientID: "sample-oauth-id"
        clientSecret: "sample-oauth-secret"
        redirectURI: https://dex.example.com/callback
        orgs:
        - name: jdvgh-gh-org
    storage:
      type: memory
    issuer: https://dex.example.com
    staticClients:
      - id: oauth2-proxy-client
        name: oauth2-proxy
        redirectURIs:
          - 'https://nginx.example.com/oauth2/callback'
          - 'https://echo-server.example.com/oauth2/callback'
          - 'https://kiali.example.com/oauth2/callback'
          - 'https://jaeger.example.com/oauth2/callback'
          - 'https://prometheus.example.com/oauth2/callback'
          - 'http://jaeger.example.com/oauth2/callback'
          - 'http://prometheus.example.com/oauth2/callback'
          - 'http://nginx.example.com/oauth2/callback'
          - 'http://echo-server.example.com/oauth2/callback'
          - 'http://kiali.example.com/oauth2/callback'
          - 'https://dex.example.com/callback'
        secret: proxy-pw
    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the password string "test"
        hash: $2a$12$WPWwjJ0KD8zI5Cw7qj2Bpu8fZnaY7MbhN/eMzJMOeY4cdNEZTUja.
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  service:
    # -- Annotations to be added to the service.
    annotations: {}

    # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
    type: ClusterIP

    # -- Internal cluster service IP (when applicable)
    clusterIP: ""

    ports:
      http:
        # -- HTTP service port
        port: 5556

        # -- (int) HTTP node port (when applicable)
        nodePort:

      https:
        # -- HTTPS service port
        port: 5554

        # -- (int) HTTPS node port (when applicable)
        nodePort:

      grpc:
        # -- gRPC service port
        port: 5557

        # -- (int) gRPC node port (when applicable)
        nodePort:

  ingress:
    # -- Enable [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
    enabled: false
